### ISSUE TITLE
Run button stops responding after sending a payload

### ISSUE THREAD

**Issue by evilpacket** [O-MG/O.MG_Cable-Firmware#3]
I've tried this with both a desktop chrome browser as well as brave on mobile. When I run a  payload I can't get the run button to respond again. 

Work around:
To get it to respond I have to remove the `#` from the url and reload the application.

Steps to reproduce.
1. plug in O.MG cable 
2. connect to the AP
3. navigate to 192.168.4.1
4. load the basic mac terminal 
5. Run the payload
6. attempt to run the payload again
...run button has stopped working at this point and won't execute more payloads.

Remove `#` from url and hit enter. Application now works as intended.

**Comment by O-MG** [comment]
weird, I cannot reproduce this. 
is anything being added to the contents of the payload area that make it invalid? How long are you waiting after running?

**Comment by 0xd3d0c3d** [comment]
the run button is disabled while the previous payload is still executing. otherwise while the first payload still running is incomplete, the 2nd starts running and jumbling the payloads. wait until the hud indicators are finished before running a second payload, plz update to the newer 1.4.0 firmware here https://github.com/O-MG/O.MG_Cable-Firmware/releases/tag/v1.4.0 and let me know if you still have the issue you were having.

**Comment by 0xd3d0c3d** [comment]
> I've tried this with both a desktop chrome browser as well as brave on mobile. When I run a payload I can't get the run button to respond again.
> 
> Work around:
> To get it to respond I have to remove the `#` from the url and reload the application.
> 
> Steps to reproduce.
> 
> 1. plug in O.MG cable
> 2. connect to the AP
> 3. navigate to 192.168.4.1
> 4. load the basic mac terminal
> 5. Run the payload
> 6. attempt to run the payload again
>    ...run button has stopped working at this point and won't execute more payloads.
> 
> Remove `#` from url and hit enter. Application now works as intended.

the run button is disabled while the previous payload is still executing. otherwise while the first payload still running is incomplete, the 2nd starts running and jumbling the payloads. wait until the hud indicators are finished before running a second payload, plz update to the newer 1.4.0 firmware here: https://github.com/O-MG/O.MG_Cable-Firmware/releases/tag/v1.4.0
